public/js/js_listar_revisores.js, resources/views/coordenador/revisores/listarRevisores.blade.php
- Botão de marcar ou desmarcar todas as áreas em novo revisor
- Botão de marcar ou desmarcar todas as modalidades em novo revisor
- Botão de marcar ou desmarcar todas as áreas em editar revisor
- Botão de marcar ou desmarcar todas as modalidades em editar revisor
=> Botão de marcar ou desmarcar em listar revisores

app/Exports/InscritosExport.php, app/Http/Controllers/Inscricao/InscricaoController.php, app/Models/Submissao/Evento.php, resources/views/coordenador/areas/listarAreas.blade.php, resources/views/coordenador/detalhesEvento.blade.php, resources/views/coordenador/evento/arquivoInfo/arquivoInfo.blade.php, resources/views/coordenador/inscritos.blade.php, routes/web.php
Resolve #208 , resolve #209 , resolve #211
=> Ajustes no menu e na tela de listagem dos inscritos

app/Http/Controllers/Inscricao/InscricaoController.php, app/Http/Controllers/Submissao/EventoController.php, resources/views/coordenador/detalhesEvento.blade.php, resources/views/evento/visualizarEvento.blade.php, routes/web.php
Resolve #213 , ajusta permissões da listagem de inscritos e remove espaços em branco no nome do item no menu.
=> Ajusta rota de visualizar evento e correções menores

app/Http/Controllers/Submissao/TrabalhoController.php, app/Http/Requests/TrabalhoPostRequest.php, app/Policies/EventoPolicy.php, resources/views/evento/submeterTrabalho.blade.php
=> Membro da comissao pode alterar autor na submissao

app/Http/Controllers/Submissao/EventoController.php
=> Corrige funcionalidade de exportar avaliações em csv

resources/views/evento/submeterTrabalho.blade.php
This reverts commit c773da75fb2b5c4581698d0a2a9c9591b952c5cd.
=> Revert "refatora o código com alpinejs"

resources/views/coordenador/trabalhos/mensagensParecer.blade.php
=> corrige acesso a array

app/Http/Controllers/Submissao/AtribuicaoController.php, app/Http/Controllers/Submissao/EventoController.php, app/Http/Controllers/Submissao/TrabalhoController.php, app/Http/Controllers/Users/RevisorController.php, app/Http/Controllers/Users/UserController.php, app/Models/Submissao/Trabalho.php, resources/views/coordenador/trabalhos/listarRespostas.blade.php, resources/views/coordenador/trabalhos/listarRespostasTrabalhos.blade.php, resources/views/coordenador/trabalhos/visualizarRespostaFormulario.blade.php, resources/views/revisor/index.blade.php, resources/views/user/meusTrabalhos.blade.php, resources/views/user/perfilUser.blade.php, resources/views/user/visualizarParecer.blade.php, routes/web.php
=> Correções para múltiplos avaliadores

app/Models/Submissao/Trabalho.php, resources/views/coordenador/trabalhos/listarTrabalhos.blade.php, resources/views/coordenador/trabalhos/listarTrabalhosModalidades.blade.php
=> informa a qtd de avaliações do trabalho

resources/views/coordenador/palestrante/create.blade.php
=> permitir numeros em titulo de palestra

resources/views/coordenador/certificado/edit.blade.php
=> tamanho padrao para imagem em editar certificado

resources/views/coordenador/certificado/modelo.blade.php
=> correcao de texto - decode html em visualizar modelo do certificado

app/Console/Commands/AtualizarExibirProgramacao.php, app/Http/Controllers/Submissao/FormEventoController.php, database/migrations/2022_08_08_210425_add_exibir_pdf_to_eventos.php, resources/views/coordenador/detalhesEvento.blade.php, resources/views/coordenador/evento/modulos.blade.php, resources/views/evento/visualizarEvento.blade.php
=> Permite mostrar a programação em arquivo e calendário

app/Http/Controllers/Submissao/ModalidadeController.php, app/Http/Controllers/Submissao/TrabalhoController.php, app/Http/Requests/TrabalhoPostRequest.php, app/Http/Requests/TrabalhoUpdateRequest.php, app/Models/Submissao/Modalidade.php, app/Rules/FileType.php, database/migrations/2022_10_24_093215_add_mp4_and_mp3_to_modalidades_table.php, resources/views/coordenador/modalidade/cadastrarModalidade.blade.php, resources/views/coordenador/modalidade/listarModalidade.blade.php, resources/views/coordenador/trabalhos/trabalho_edit.blade.php, resources/views/evento/submeterTrabalho.blade.php, resources/views/user/meusTrabalhos.blade.php
=> Submeter arquivo de trabalho como mp3 ou mp4

app/Http/Controllers/Submissao/EventoController.php, resources/views/coordenador/trabalhos/listarTrabalhos.blade.php
=> ordenação por data de submissão

app/Models/Submissao/Evento.php, app/Models/Users/Revisor.php, resources/lang/pt-BR/messages.php, resources/views/coordenador/trabalhos/listarTrabalhos.blade.php
=> mostra a qtd de avaliações pendentes

app/Http/Controllers/Submissao/CertificadoController.php, app/Http/Requests/CertificadoRequest.php, app/Http/Requests/UpdateCertificadoRequest.php, app/Models/Submissao/Certificado.php, database/migrations/2023_05_19_112310_adiciona_checkbox_to_certificados.php, resources/views/coordenador/certificado/certificado_preenchivel.blade.php, resources/views/coordenador/certificado/create.blade.php, resources/views/coordenador/certificado/edit.blade.php, resources/views/coordenador/certificado/modelo.blade.php
Permite o usuário enviar a imagem do certificado com as assinaturas
=> Adiciona opção de não selecionar assinaturas

app/Http/Controllers/Auth/RegisterController.php, app/Http/Controllers/Submissao/EventoController.php, app/Http/Controllers/Users/UserController.php, app/Models/Users/User.php, database/migrations/2023_11_06_154720_add_cnpj_to_users_table.php, public/css/home/home.css, resources/views/auth/register.blade.php, resources/views/componentes/footer.blade.php, resources/views/componentes/modal.blade.php, resources/views/coordenador/certificado/create.blade.php, resources/views/coordenador/detalhesEvento.blade.php, resources/views/coordenador/evento/eventosProximos.blade.php, resources/views/coordenador/informacoes.blade.php, resources/views/coordenador/modalidade/respostasPdf.blade.php, resources/views/coordenador/modalidade/visualizarRespostas.blade.php, resources/views/coordenador/revisores/listarRevisores.blade.php, resources/views/coordenador/revisores/listarUsuarios.blade.php, resources/views/coordenador/revisores/revisoresCadastrados.blade.php, resources/views/coordenador/trabalhos/distribuirLote.blade.php, resources/views/coordenador/trabalhos/listarRespostasTrabalhos.blade.php, resources/views/coordenador/trabalhos/listarTrabalhos.blade.php, resources/views/coordenador/trabalhos/listarTrabalhosModalidades.blade.php, resources/views/coordenador/trabalhos/resultados.blade.php, resources/views/coordenador/trabalhos/visualizarRespostaFormulario.blade.php, resources/views/evento/visualizarEvento.blade.php, resources/views/index.blade.php, resources/views/navbar.blade.php, resources/views/tables/table_users.blade.php, resources/views/user/perfilUser.blade.php, routes/web.php
issues do participa 
- retirar navegação do footer (inicio etc)
-colocar underline quando passar mouse por cima nos links para ultimos eventos realizados 
-criar uma view (igual a de "ultimos eventos realizados" ) para todos os 
eventos com link no primeiro slide 
- mudança de termos (onde tiver 'revisor" colocar "avaliador")
-colocar alguma observação para dar "dica" no sistema 
- No cadastro de usuario, disponibilizar que utilize passaporte, cpf ou cnpj
=> alterações no front + cnpj no cadastro de usuario

app/Http/Requests/TrabalhoPostRequest.php, app/Http/Requests/TrabalhoUpdateRequest.php
os coautores precisam estar cadastrados no sistema
=> validacao de usuario do coautor cadastrado

app/Models/Inscricao/Pagamento.php
(cherry picked from commit 1c52a1e89c3a4b0104a04b66ec5e0f3902a8d675)
=> corrige relacionamento entre tipo e pagamento

app/Http/Controllers/Submissao/EventoController.php, resources/views/coordenador/informacoes.blade.php
=> adiciona infos da inscricoes, trabalhos por modalidade e atividades

app/Http/Controllers/Submissao/EventoController.php, resources/views/components/modal-excluir-evento.blade.php, resources/views/coordenador/home.blade.php, resources/views/coordenador/index.blade.php, resources/views/evento/visualizarEvento.blade.php, routes/web.php
=> pede confirmacao do email do coordenador para excluir

app/Http/Controllers/Submissao/TrabalhoController.php, resources/views/components/modal-excluir-trabalho.blade.php, resources/views/coordenador/trabalhos/listarTrabalhos.blade.php, resources/views/coordenador/trabalhos/listarTrabalhosModalidades.blade.php, resources/views/user/meusTrabalhos.blade.php
=> permite coordenador excluir trabalho

resources/views/revisor/formularioRevisor.blade.php
=> mostra informacoes do evento, trabalho e area

app/Http/Controllers/Submissao/EventoController.php, app/Http/Controllers/Submissao/ModalidadeController.php, app/Http/Requests/ModalidadeStoreRequest.php, app/Http/Requests/StoreEventoRequest.php, public/css/app.css, resources/lang/pt-BR/validation.php, resources/views/auth/login.blade.php, resources/views/coordenador/index.blade.php, resources/views/coordenador/modalidade/listarModalidade.blade.php, resources/views/evento/criarEvento.blade.php, resources/views/evento/modal-areas.blade.php, resources/views/evento/modal-inscricao.blade.php, resources/views/evento/visualizarEvento.blade.php, resources/views/navbar.blade.php
- Correção na view de login: Tamanho do texto principal e alteração de 'Endereço de email' Para 'Email'
- Corrigindo o modal onde aparece as categorias na inscrição de um evento
- O botão de trabalhos só vai aparecer se o user já tiver algum trabalho submetido como autor ou coautor ( A lógica de todos os links da navbar estão na própria view então usei a mesma logica)
- O arquivo de regras na modalidade agora pode ter 10mb
- As imagens de banner e ícone são obrigatórias  ao criar um evento
=> Algumas correções da ultima reunião

app/Http/Controllers/Submissao/ModalidadeController.php, app/Http/Controllers/Submissao/TrabalhoController.php, app/Http/Requests/ModalidadeStoreRequest.php, app/Http/Requests/TrabalhoPostRequest.php, app/Models/Submissao/Modalidade.php, app/Rules/MaxCoautoresNaModalidade.php, database/migrations/2025_05_24_224540_add_num_max_trabalhos_and_num_max_coautores_to_modalidades_table.php, resources/lang/en.json, resources/lang/es.json, resources/views/coordenador/modalidade/cadastrarModalidade.blade.php, resources/views/coordenador/modalidade/listarModalidade.blade.php, resources/views/evento/modal-areas.blade.php, resources/views/evento/submeterTrabalho.blade.php, resources/views/evento/visualizarEvento.blade.php, routes/web.php
- Foi alterado alguns nomes na view de visualizar evento que a comissão pediu
- Criada a migration que adiciona a coluna na entidade modalidade
- Alteração nas views de controllers que interferem no envio
=> Adicionando funcionalidade de numero máximo de coautores na modalidade

resources/views/evento/modal-areas.blade.php, resources/views/evento/visualizarEvento.blade.php
=> Regex para mudar apenas a palavra 'Eixo' para negrito nas áreas temáticas 

.gitignore, resources/views/componentes/footer.blade.php, resources/views/evento/editarEvento.blade.php, resources/views/navbar.blade.php
Implementação de nova identidade visual da plataforma com esquema de cores verde e adiciona validação no frontend para campos obrigatórios na edição de eventos, melhorando tanto a experiência visual quanto a usabilidade.
---
- Atualização completa do esquema de cores para verde escuro (#114048) - Padrão do Figma
- Adição de seção de redes sociais no footer
- Modernização do layout geral da plataforma
- Implementação de validação JavaScript para campos obrigatórios
- Mensagens de erro em tempo real
- Prevenção de avanço sem preenchimento dos campos necessários
---
```
modificado: resources/views/navbar.blade.php
modificado: resources/views/componentes/footer.blade.php
modificado: resources/views/evento/editarEvento.blade.php
added: public/img/email-icon.png
added: …
```
=> adicionado validação no frontend + Edição do Navbar + Edição do Footer

resources/views/coordenador/modalidade/cadastrarModalidade.blade.php, resources/views/evento/criarEvento.blade.php, resources/views/evento/editarEvento.blade.php
Esta PR implementa melhorias significativas na experiência do usuário no formulário de cadastro de modalidades, focando em correções de bugs, melhorias visuais e aprimoramentos de usabilidade.
- **Ícones Informativos**: Adicionados ícones de informação aos campos opcionais para melhor orientação do usuário
- **Layout Responsivo**: Reposicionamento do checkbox "Evento Multilíngue" para o canto direito da tela, criando melhor equilíbrio visual
- **Alinhamento de Elementos**: Otimização do posicionamento dos radio buttons de tipo de evento (Online/Presencial/Híbrido)
- **Alpine.js**: Corrigido erro de variável `submissaoUnica` não definida que estava causando problemas no console
- **Validação de Formulário**: Ajustes na validação client-side para melhor feedback ao usuário
- …
=> Melhora UX do formulário: adiciona ícones informativos, corrige posicionamento de elementos e resolve erros do Alpine.js

app/Http/Controllers/Inscricao/InscricaoController.php, resources/views/coordenador/inscricoes/inscritos.blade.php, routes/web.php
Foi adicionado um botão na view de inscrição do coordenador para alterar o status do campo alimentação de um inscrito em especifico.
=> feat: Botão para adicionar alimentação aos inscritos
